spring:
  datasource:
    name: writeln-backend
    url: jdbc:postgresql://localhost:3306/writeln
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database: postgresql