spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/matchreal
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
